version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: financas
      POSTGRES_USER: financas
      POSTGRES_PASSWORD: financas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: changeme-secret-key
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financas
      SPRING_DATASOURCE_USERNAME: financas
      SPRING_DATASOURCE_PASSWORD: financas
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
